<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Action_btn</name>
   <tag></tag>
   <elementGuidId>59491552-4e70-4d8e-8c04-b21e92f4dff6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;table-folder&quot;]/tbody/tr[9]/td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;table-folder&quot;]/tbody/tr[9]/td[4]</value>
   </webElementProperties>
</WebElementEntity>
