<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ClientMenu</name>
   <tag></tag>
   <elementGuidId>7ddee87e-e493-4026-97c6-c9d024efc675</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href=&quot;/Explorer/Client&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href=&quot;/Explorer/Client&quot;]</value>
   </webElementProperties>
</WebElementEntity>
